{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "ceafa70f_141fa901",
        "filename": "src/main/java/com/googlesource/gerrit/modules/cache/chroniclemap/ChronicleMapCacheImpl.java",
        "patchSetId": 3
      },
      "lineNbr": 332,
      "author": {
        "id": 1054778
      },
      "writtenOn": "2022-01-10T14:35:43Z",
      "side": 1,
      "message": "Seems like we are returning a boolean which we don\u0027t use later on, which makes sense since I would expect the API to be similar to the wrapped `put`",
      "range": {
        "startLine": 332,
        "startChar": 16,
        "endLine": 332,
        "endChar": 23
      },
      "revId": "a5c5b2fae8b74b7f719f6099e02df2da0890aee1",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "78a79e39_ced896b6",
        "filename": "src/main/java/com/googlesource/gerrit/modules/cache/chroniclemap/ChronicleMapCacheImpl.java",
        "patchSetId": 3
      },
      "lineNbr": 332,
      "author": {
        "id": 1054778
      },
      "writtenOn": "2022-01-10T14:35:43Z",
      "side": 1,
      "message": "nit: what about calling `tryPut` since it is basically surrounding a `put` with a `try...catch`.\n\nHowever, this is just a personal preference.",
      "range": {
        "startLine": 332,
        "startChar": 24,
        "endLine": 332,
        "endChar": 34
      },
      "revId": "a5c5b2fae8b74b7f719f6099e02df2da0890aee1",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "4f26bae0_d39df099",
        "filename": "src/test/java/com/googlesource/gerrit/modules/cache/chroniclemap/ChronicleMapCacheTest.java",
        "patchSetId": 3
      },
      "lineNbr": 361,
      "author": {
        "id": 1054778
      },
      "writtenOn": "2022-01-10T14:35:43Z",
      "side": 1,
      "message": "Which exception is this test catching? Since we are handling 2 exceptions (`IllegalArgumentException` and `IllegalStateException`), I was expecting 2 tests.\n\nAm I missing something?",
      "revId": "a5c5b2fae8b74b7f719f6099e02df2da0890aee1",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    }
  ]
}